/// <reference types="react" />
import { Loading, Animate, FlipCard } from './lib/animations/animations';
import { Calendar } from './lib/calendar/calendar';
import { CheckBox } from './lib/checkboxes/checkboxes';
import { BasicSelect, AdvancedSelect } from './lib/dropdownlists/dropdownlists';
import { CircularGraph } from './lib/graphs/graphs';
import { MenuWithBlur } from './lib/menus/menus';
import { Modal } from './lib/modals/modals';
import { RadioButton, RadioButtonsGroup } from './lib/radiobuttons/radiobuttons';
import { TextBox } from './lib/textboxes/textboxes';
import { Tabs } from './lib/tabs/tabs';
import { ToastNotification } from './lib/toastnotifications/toastnotifications';
import { ToolTip } from './lib/tooltip/tooltip';
declare const _default: {
    Animate: typeof Animate;
    Badge: import("styled-components").StyledComponent<"label", any, import("./lib/badges/badges").IBadgeProps, never>;
    Button: import("styled-components").StyledComponent<"button", any, import("./lib/buttons/buttons").IButtonProps, never>;
    Calendar: typeof Calendar;
    Card: import("styled-components").StyledComponent<"div", any, import("./lib/cards/cards").ICardProps, never>;
    CheckBox: typeof CheckBox;
    CircularGraph: typeof CircularGraph;
    FlipCard: typeof FlipCard;
    FrontContent: import("styled-components").StyledComponent<"div", any, import("react").HTMLProps<HTMLDivElement>, never>;
    BackContent: import("styled-components").StyledComponent<"div", any, import("react").HTMLProps<HTMLDivElement>, never>;
    Icon: import("styled-components").StyledComponent<"svg", any, import("./lib/icons/icons").IIconProps & import("react").SVGProps<SVGSVGElement>, never>;
    IconBadge: import("styled-components").StyledComponent<"label", any, import("./lib/badges/badges").IIconBadgeProps, never>;
    IconButton: import("styled-components").StyledComponent<"button", any, import("./lib/buttons/buttons").IIconButtonProps, never>;
    Loading: typeof Loading;
    MenuWithBlur: typeof MenuWithBlur;
    Modal: typeof Modal;
    ModalHeader: import("styled-components").StyledComponent<"div", any, import("react").HTMLProps<HTMLDivElement>, never>;
    ModalTitle: import("styled-components").StyledComponent<"label", any, import("react").HTMLProps<HTMLLabelElement>, never>;
    ModalBody: import("styled-components").StyledComponent<"div", any, import("react").HTMLProps<HTMLDivElement>, never>;
    ModalFooter: import("styled-components").StyledComponent<"div", any, import("react").HTMLProps<HTMLDivElement>, never>;
    NotificationBadge: import("styled-components").StyledComponent<"div", any, import("./lib/badges/badges").INotificationBadgeProps & import("react").HTMLProps<HTMLDivElement>, never>;
    Select: typeof BasicSelect;
    AdvancedSelect: typeof AdvancedSelect;
    RadioButton: typeof RadioButton;
    RadioButtonsGroup: typeof RadioButtonsGroup;
    RoundButton: import("styled-components").StyledComponent<"button", any, import("./lib/buttons/buttons").IIconButtonProps, never>;
    Tabs: typeof Tabs;
    TextBox: typeof TextBox;
    ToastNotification: typeof ToastNotification;
    ToolTip: typeof ToolTip;
};
export = _default;
